name: CI

on:
  push:
  pull_request:

jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php }} ${{ matrix.event-loop }})
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        event-loop:
          - ''
          - 'event'
          - 'uv'
        php:
          - 8.1
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          extensions: socket
      - run: sudo apt-get update && sudo apt-get install libevent-dev
      - name: Install ext-event
        run: |
          echo "yes" | sudo pecl install event
          echo "extension=event.so" | sudo tee -a "$(php -r 'echo php_ini_loaded_file();')"
        if: ${{ matrix.event-loop == 'event' }}
      - name: Install ext-uv
        run: |
          sudo add-apt-repository ppa:ondrej/php -y && sudo apt-get update -q && sudo apt-get install libuv1-dev
          echo "yes" | sudo pecl install uv-beta
          echo "extension=uv.so" >> "$(php -r 'echo php_ini_loaded_file();')"
        if: ${{ matrix.event-loop == 'uv' }}
      - run: composer install
      - run: vendor/bin/phpunit --coverage-text
